from enum import Enum

class LanguageCodes(Enum):
    ENGLISH = "EN"
    HINDI = "HI"
    BENGALI = "BN"
    GUJARATI = "GU"
    MARATHI = "MR"
    ORIYA = "OR"
    PUNJABI = "PA"
    KANNADA = "KN"
    MALAYALAM = "ML"
    TAMIL = "TA"
    TELUGU = "TE"
    AFRIKAANS = "AF"
    ARABIC = "AR"
    CHINESE = "ZH"
    FRENCH = "FR"
    GERMAN = "DE"
    INDONESIAN = "ID"
    ITALIAN = "IT"
    JAPANESE = "JA"
    KOREAN = "KO"
    PORTUGUESE = "PT"
    RUSSIAN = "RU"
    SPANISH = "ES"
    TURKISH = "TR"

class LanguageMapping(Enum):
    ENGLISH = "English"
    HINDI = "हिंदी"
    BENGALI = "বাংলা"
    GUJARATI = "ગુજરાતી"
    MARATHI = "मराठी"
    ORIYA = "ଓଡିଆ"
    PUNJABI = "ਪੰਜਾਬੀ"
    KANNADA = "ಕನ್ನಡ"
    MALAYALAM = "മലയാളം"
    TAMIL = "தமிழ்"
    TELUGU = "తెలుగు"
    AFRIKAANS = "Afrikaans"
    ARABIC = "عربي"
    CHINESE = "中国人"
    FRENCH = "French"
    GERMAN = "Deutsch"
    INDONESIAN = "bahasa Indonesia"
    ITALIAN = "Italiana"
    JAPANESE = "日本語"
    KOREAN = "한국인"
    PORTUGUESE = "português"
    RUSSIAN = "Русский"
    SPANISH = "Español"
    TURKISH = "Türkçe"