"""added_retriever_logger

Revision ID: 0691bed1718d
Revises: 0c7ec476bb6a
Create Date: 2024-11-13 14:46:02.812866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0691bed1718d'
down_revision = '75ede3eb2904'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jb_retriever_logger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('turn_id', sa.String(), nullable=True),
    sa.Column('msg_id', sa.String(), nullable=True),
    sa.Column('retriever_type', sa.String(), nullable=True),
    sa.Column('collection_name', sa.String(), nullable=True),
    sa.Column('number_of_chunks', sa.String(), nullable=True),
    sa.Column('chunks', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['jb_api_logger.turn_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jb_retriever_logger')
    # ### end Alembic commands ###
