"""added jb_admins table

Revision ID: 078d11b16dbc
Revises: 1928ed398bc2
Create Date: 2024-03-05 15:05:00.967757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078d11b16dbc'
down_revision = '1928ed398bc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jb_admins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('jb_secret', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jb_bot', sa.Column('created_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'jb_bot', 'jb_admins', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jb_bot', type_='foreignkey')
    op.drop_column('jb_bot', 'created_by')
    op.drop_table('jb_admins')
    # ### end Alembic commands ###
