"""added_flow_logger

Revision ID: 0c7ec476bb6a
Revises: 61e2bc9dea1c
Create Date: 2024-11-05 15:55:30.661813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7ec476bb6a'
down_revision = '61e2bc9dea1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jb_flow_logger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('turn_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('msg_id', sa.String(), nullable=True),
    sa.Column('msg_intent', sa.String(), nullable=True),
    sa.Column('flow_intent', sa.String(), nullable=True),
    sa.Column('response_model_used', sa.String(), nullable=True),
    sa.Column('model_response_time', sa.String(), nullable=True),
    sa.Column('tokens', sa.String(), nullable=True),
    sa.Column('sent_to_service', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['jb_api_logger.turn_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jb_flow_logger')
    # ### end Alembic commands ###
