"""Updated JB Session

Revision ID: 1c6f51f026b9
Revises: a21d0cb3413a
Create Date: 2024-07-15 01:53:14.375503

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1c6f51f026b9"
down_revision = "a21d0cb3413a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jb_bot", "channels")
    op.add_column("jb_session", sa.Column("user_id", sa.String(), nullable=True))
    op.add_column("jb_session", sa.Column("channel_id", sa.String(), nullable=True))
    op.create_foreign_key(None, "jb_session", "jb_users", ["user_id"], ["id"])
    op.create_foreign_key(None, "jb_session", "jb_channel", ["channel_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "jb_session", type_="foreignkey")
    op.drop_constraint(None, "jb_session", type_="foreignkey")
    op.drop_column("jb_session", "channel_id")
    op.drop_column("jb_session", "user_id")
    op.add_column(
        "jb_bot",
        sa.Column(
            "channels",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
