"""updated_retriever_and_api_logger

Revision ID: 2e773b3253b6
Revises: 0691bed1718d
Create Date: 2024-11-15 16:05:49.901151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e773b3253b6'
down_revision = '0691bed1718d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jb_api_logger', 'msg_id')
    op.add_column('jb_retriever_logger', sa.Column('top_chunk_k_value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jb_retriever_logger', 'top_chunk_k_value')
    op.add_column('jb_api_logger', sa.Column('msg_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
