"""initial db

Revision ID: 5379fddfdecf
Revises: 
Create Date: 2024-01-25 13:38:27.114902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5379fddfdecf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jb_bot',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('channels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config_env', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('jb_chat_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pid', sa.String(), nullable=True),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('document_uuid', sa.String(), nullable=True),
    sa.Column('message_owner', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('message_in_english', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jb_document_store_log',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('documents_list', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('total_file_size', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('jb_fsm_state',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pid', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jb_message',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('user_text', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('is_valid_message_type', sa.Boolean(), nullable=True),
    sa.Column('is_user_sent', sa.Boolean(), nullable=False),
    sa.Column('db_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jb_qa_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pid', sa.String(), nullable=True),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('document_uuid', sa.String(), nullable=True),
    sa.Column('input_language', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('audio_input_link', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('audio_output_link', sa.String(), nullable=True),
    sa.Column('retrieval_k_value', sa.Integer(), nullable=True),
    sa.Column('retrieved_chunks', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('gpt_model_name', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jb_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pid', sa.String(), nullable=True),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jb_stt_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('qa_log_id', sa.String(), nullable=True),
    sa.Column('audio_input_bytes', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jb_translator_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('qa_log_id', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('input_language', sa.String(), nullable=True),
    sa.Column('output_language', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('translated_text', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jb_tts_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('qa_log_id', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('audio_output_bytes', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jb_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('language_preference', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jb_users')
    op.drop_table('jb_tts_log')
    op.drop_table('jb_translator_log')
    op.drop_table('jb_stt_log')
    op.drop_table('jb_session')
    op.drop_table('jb_qa_log')
    op.drop_table('jb_message')
    op.drop_table('jb_fsm_state')
    op.drop_table('jb_document_store_log')
    op.drop_table('jb_chat_history')
    op.drop_table('jb_bot')
    # ### end Alembic commands ###
