"""added_language_logger

Revision ID: 61e2bc9dea1c
Revises: ce6e6c51c532
Create Date: 2024-10-28 14:31:51.184384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e2bc9dea1c'
down_revision = 'ce6e6c51c532'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jb_language_logger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('turn_id', sa.String(), nullable=True),
    sa.Column('msg_id', sa.String(), nullable=True),
    sa.Column('msg_state', sa.String(), nullable=True),
    sa.Column('msg_language', sa.String(), nullable=True),
    sa.Column('msg_type', sa.String(), nullable=True),
    sa.Column('translated_to_language', sa.String(), nullable=True),
    sa.Column('translation_type', sa.String(), nullable=True),
    sa.Column('model_for_translation', sa.String(), nullable=True),
    sa.Column('response_time', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['jb_api_logger.turn_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jb_language_logger')
    # ### end Alembic commands ###
