"""

Revision ID: 68e836bbcaa0
Revises: a9627532e831
Create Date: 2024-02-22 19:44:55.368829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68e836bbcaa0'
down_revision = 'a9627532e831'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jb_bot', sa.Column('index_urls', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jb_bot', 'index_urls')
    # ### end Alembic commands ###
