"""update_api_logger

Revision ID: 6bfbb039a05d
Revises: fe0b2e850214
Create Date: 2024-10-24 14:57:39.097826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfbb039a05d'
down_revision = 'fe0b2e850214'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jb_api_logger',
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('msg_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('turn_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jb_api_logger')
    # ### end Alembic commands ###
