"""Adding JB turn

Revision ID: 755ad3370d08
Revises: d14a309a415d
Create Date: 2024-01-26 13:19:54.333365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '755ad3370d08'
down_revision = 'd14a309a415d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jb_turn',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('turn_type', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jb_message', sa.Column('message_type', sa.String(), nullable=True))
    op.add_column('jb_message', sa.Column('message_text', sa.String(), nullable=True))
    op.drop_column('jb_message', 'db_created_at')
    op.drop_column('jb_message', 'bot_id')
    op.drop_column('jb_message', 'user_text')
    op.drop_column('jb_message', 'user_created_at')
    op.drop_column('jb_message', 'media_type')
    op.drop_column('jb_message', 'session_id')
    op.drop_column('jb_message', 'is_valid_message_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jb_message', sa.Column('is_valid_message_type', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('jb_message', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jb_message', sa.Column('media_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jb_message', sa.Column('user_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('jb_message', sa.Column('user_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jb_message', sa.Column('bot_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jb_message', sa.Column('db_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('jb_message', 'message_text')
    op.drop_column('jb_message', 'message_type')
    op.drop_table('jb_turn')
    # ### end Alembic commands ###
