"""updated_flow_logger

Revision ID: 75ede3eb2904
Revises: 0c7ec476bb6a
Create Date: 2024-11-13 18:08:50.717829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ede3eb2904'
down_revision = '0c7ec476bb6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jb_flow_logger', 'tokens')
    op.drop_column('jb_flow_logger', 'response_model_used')
    op.drop_column('jb_flow_logger', 'model_response_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jb_flow_logger', sa.Column('model_response_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jb_flow_logger', sa.Column('response_model_used', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jb_flow_logger', sa.Column('tokens', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
