"""modify jb bot to include code

Revision ID: 805244467ae1
Revises: b3cab21a430d
Create Date: 2024-02-13 14:19:24.222232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '805244467ae1'
down_revision = 'b3cab21a430d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jb_bot', sa.Column('dsl', sa.String(), nullable=True))
    op.add_column('jb_bot', sa.Column('fsm', sa.String(), nullable=True))
    op.add_column('jb_bot', sa.Column('requirements', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jb_bot', 'requirements')
    op.drop_column('jb_bot', 'fsm')
    op.drop_column('jb_bot', 'dsl')
    # ### end Alembic commands ###
