"""Modify jbbot

Revision ID: 8fc0a0f4f22d
Revises: 805244467ae1
Create Date: 2024-02-21 16:23:59.606472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc0a0f4f22d'
down_revision = '805244467ae1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jb_bot', sa.Column('fsm_code', sa.String(), nullable=True))
    op.add_column('jb_bot', sa.Column('requirements_txt', sa.String(), nullable=True))
    op.add_column('jb_bot', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('jb_bot', 'fsm')
    op.drop_column('jb_bot', 'requirements')
    op.create_foreign_key(None, 'jb_message', 'jb_turn', ['turn_id'], ['id'])
    op.create_foreign_key(None, 'jb_session', 'jb_users', ['pid'], ['id'])
    op.create_foreign_key(None, 'jb_session', 'jb_bot', ['bot_id'], ['id'])
    op.create_foreign_key(None, 'jb_turn', 'jb_session', ['session_id'], ['id'])
    op.create_foreign_key(None, 'jb_turn', 'jb_bot', ['bot_id'], ['id'])
    op.create_foreign_key(None, 'jb_users', 'jb_bot', ['bot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jb_users', type_='foreignkey')
    op.drop_constraint(None, 'jb_turn', type_='foreignkey')
    op.drop_constraint(None, 'jb_turn', type_='foreignkey')
    op.drop_constraint(None, 'jb_session', type_='foreignkey')
    op.drop_constraint(None, 'jb_session', type_='foreignkey')
    op.drop_constraint(None, 'jb_message', type_='foreignkey')
    op.add_column('jb_bot', sa.Column('requirements', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jb_bot', sa.Column('fsm', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('jb_bot', 'updated_at')
    op.drop_column('jb_bot', 'requirements_txt')
    op.drop_column('jb_bot', 'fsm_code')
    # ### end Alembic commands ###
