"""Updated JB Message

Revision ID: a21d0cb3413a
Revises: a940da779e11
Create Date: 2024-07-15 00:41:34.955648

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a21d0cb3413a"
down_revision = "a940da779e11"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jb_message",
        sa.Column("message", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    op.drop_column("jb_message", "channel")
    op.drop_column("jb_message", "channel_id")
    op.drop_column("jb_message", "message_text")
    op.drop_column("jb_message", "media_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jb_message",
        sa.Column("media_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "jb_message",
        sa.Column("message_text", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "jb_message",
        sa.Column("channel_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "jb_message",
        sa.Column("channel", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("jb_message", "message")
    # ### end Alembic commands ###
