"""Added turn id

Revision ID: b3cab21a430d
Revises: 4d4d92ab085b
Create Date: 2024-02-05 12:50:02.745651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3cab21a430d'
down_revision = '4d4d92ab085b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jb_plugin_uuid', sa.Column('turn_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jb_plugin_uuid', 'turn_id')
    # ### end Alembic commands ###
