"""Added turnId

Revision ID: d14a309a415d
Revises: 5379fddfdecf
Create Date: 2024-01-25 17:16:04.570130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd14a309a415d'
down_revision = '5379fddfdecf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jb_message', sa.Column('turn_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jb_message', 'turn_id')
    # ### end Alembic commands ###
